services:
  # 1. THE LOG DATABASE
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100" # Loki API port
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - arc_net

  # 2. THE VISUALIZATION
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Grafana UI
    volumes:
      # This is the "magic" to auto-add Loki as a datasource
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
    networks:
      - arc_net

  # 3. THE "INTERFACE" (OUR OTel COLLECTOR)
  otel-collector:
    build:
      context: ./config/otel-collector
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "13133:13133" # Health Check extension
    healthcheck:
      test: ["CMD", "/health_check", "http://localhost:13133"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      - loki
    networks:
      - arc_net

  prometheus:
    image: prom/prometheus:latest # Using latest for simplicity
    container_name: prometheus
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - arc_net

  jaeger:
    image: jaegertracing/all-in-one:latest # Using latest for simplicity
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      # OTLP ports for Jaeger to receive traces directly if needed
      - "4317"
      - "4318"
    networks:
      - arc_net

  swiss-army-go:
    build:
      context: ./services/swiss-army
    container_name: swiss-army-go
    depends_on:
      otel-collector:
        condition: service_healthy
    environment:
      # This is the "contract". Same env var, same endpoint.
      # Pointing to the gRPC port for the Go app's exporters.
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=swiss-army-go
    networks:
      - arc_net


networks:
  arc_net:
    driver: bridge