name: üõ°Ô∏è Mirror - Gateway

on:
  workflow_dispatch: 

jobs:
  sync-gateway:
    uses: ./.github/workflows/reusable-mirror.yml
    with:
      group_name: "Gateway & Identity"
      image_list: |
        traefik:latest = arc-heimdall-gateway
        unleashorg/unleash-server:latest = arc-mystique-flags
        oryd/kratos:latest = arc-deckard-identity
        infisical/infisical:latest = arc-fury-vault
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
