name: ðŸ”­ Publish - Observability

on:
  workflow_dispatch:

jobs:
  sync-observability:
    uses: ./.github/workflows/reusable-publish.yml
    with:
      group_name: 'Observability Stack'
      image_list: |
        otel/opentelemetry-collector:latest = arc-widow-otel
        prom/prometheus:latest = arc-house-metrics
        grafana/loki:latest = arc-watson-logs
        jaegertracing/all-in-one:latest = arc-columbo-traces
        grafana/grafana:latest = arc-friday-viz
        grafana/promtail:latest = arc-hermes-shipper
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
